/*
  2012-07-13 16:54 GMT
  _coffee/main.coffee > scripts/main.js
  
  created by Grifo
*/
// Generated by CoffeeScript 1.3.3
(function(){(function(){return console.log("Hello Word!")})()}).call(this);